// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriPlanner.Data;

#nullable disable

namespace NutriPlanner.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriPlanner.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCalories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCarbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalProtein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DishId");

                    b.HasIndex("UserId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("NutriPlanner.Models.DishProduct", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DishId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("DishProducts");
                });

            modelBuilder.Entity("NutriPlanner.Models.FoodDiary", b =>
                {
                    b.Property<int>("DiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaryId"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DishId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DiaryId");

                    b.HasIndex("DishId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodDiaries");
                });

            modelBuilder.Entity("NutriPlanner.Models.NutritionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<decimal>("DailyCalories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyCarbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyFat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyProtein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("NutriPlanner.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Calories = 165m,
                            Carbohydrates = 0m,
                            Category = "Мясо",
                            Fat = 3.6m,
                            ProductName = "Куриная грудка",
                            Protein = 31m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 2,
                            Calories = 250m,
                            Carbohydrates = 0m,
                            Category = "Мясо",
                            Fat = 15m,
                            ProductName = "Говядина",
                            Protein = 26m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 3,
                            Calories = 130m,
                            Carbohydrates = 28m,
                            Category = "Крупы",
                            Fat = 0.3m,
                            ProductName = "Рис вареный",
                            Protein = 2.7m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 4,
                            Calories = 132m,
                            Carbohydrates = 25m,
                            Category = "Крупы",
                            Fat = 2.3m,
                            ProductName = "Гречка",
                            Protein = 4.5m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 5,
                            Calories = 52m,
                            Carbohydrates = 14m,
                            Category = "Фрукты",
                            Fat = 0.2m,
                            ProductName = "Яблоко",
                            Protein = 0.3m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 6,
                            Calories = 242m,
                            Carbohydrates = 0m,
                            Category = "Мясо",
                            Fat = 16m,
                            ProductName = "Свинина",
                            Protein = 25m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 7,
                            Calories = 135m,
                            Carbohydrates = 0m,
                            Category = "Мясо",
                            Fat = 1m,
                            ProductName = "Индейка",
                            Protein = 29m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 8,
                            Calories = 541m,
                            Carbohydrates = 1.4m,
                            Category = "Мясо",
                            Fat = 42m,
                            ProductName = "Бекон",
                            Protein = 37m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 9,
                            Calories = 208m,
                            Carbohydrates = 0m,
                            Category = "Рыба",
                            Fat = 13m,
                            ProductName = "Лосось",
                            Protein = 20m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 10,
                            Calories = 184m,
                            Carbohydrates = 0m,
                            Category = "Рыба",
                            Fat = 6m,
                            ProductName = "Тунец",
                            Protein = 30m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 11,
                            Calories = 82m,
                            Carbohydrates = 0m,
                            Category = "Рыба",
                            Fat = 0.7m,
                            ProductName = "Треска",
                            Protein = 18m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 12,
                            Calories = 85m,
                            Carbohydrates = 0m,
                            Category = "Морепродукты",
                            Fat = 0.5m,
                            ProductName = "Креветки",
                            Protein = 20m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 13,
                            Calories = 155m,
                            Carbohydrates = 1.1m,
                            Category = "Яйца",
                            Fat = 11m,
                            ProductName = "Яйцо куриное",
                            Protein = 13m,
                            Unit = "шт"
                        },
                        new
                        {
                            ProductId = 14,
                            Calories = 121m,
                            Carbohydrates = 1.8m,
                            Category = "Молочные",
                            Fat = 5m,
                            ProductName = "Творог 5%",
                            Protein = 17m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 15,
                            Calories = 404m,
                            Carbohydrates = 1.3m,
                            Category = "Молочные",
                            Fat = 34m,
                            ProductName = "Сыр Чеддер",
                            Protein = 23m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 16,
                            Calories = 52m,
                            Carbohydrates = 4.7m,
                            Category = "Молочные",
                            Fat = 2.5m,
                            ProductName = "Молоко 2.5%",
                            Protein = 2.9m,
                            Unit = "мл"
                        },
                        new
                        {
                            ProductId = 17,
                            Calories = 59m,
                            Carbohydrates = 3.6m,
                            Category = "Молочные",
                            Fat = 0.4m,
                            ProductName = "Йогурт греческий",
                            Protein = 10m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 18,
                            Calories = 68m,
                            Carbohydrates = 12m,
                            Category = "Крупы",
                            Fat = 1.4m,
                            ProductName = "Овсянка",
                            Protein = 2.4m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 19,
                            Calories = 158m,
                            Carbohydrates = 31m,
                            Category = "Крупы",
                            Fat = 0.9m,
                            ProductName = "Макароны вареные",
                            Protein = 5.8m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 20,
                            Calories = 247m,
                            Carbohydrates = 41m,
                            Category = "Хлеб",
                            Fat = 3.4m,
                            ProductName = "Хлеб цельнозерновой",
                            Protein = 13m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 21,
                            Calories = 77m,
                            Carbohydrates = 17m,
                            Category = "Овощи",
                            Fat = 0.1m,
                            ProductName = "Картофель",
                            Protein = 2m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 22,
                            Calories = 41m,
                            Carbohydrates = 10m,
                            Category = "Овощи",
                            Fat = 0.2m,
                            ProductName = "Морковь",
                            Protein = 0.9m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 23,
                            Calories = 18m,
                            Carbohydrates = 3.9m,
                            Category = "Овощи",
                            Fat = 0.2m,
                            ProductName = "Помидор",
                            Protein = 0.9m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 24,
                            Calories = 15m,
                            Carbohydrates = 3.6m,
                            Category = "Овощи",
                            Fat = 0.1m,
                            ProductName = "Огурец",
                            Protein = 0.7m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 25,
                            Calories = 34m,
                            Carbohydrates = 7m,
                            Category = "Овощи",
                            Fat = 0.4m,
                            ProductName = "Брокколи",
                            Protein = 2.8m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 26,
                            Calories = 23m,
                            Carbohydrates = 3.6m,
                            Category = "Овощи",
                            Fat = 0.4m,
                            ProductName = "Шпинат",
                            Protein = 2.9m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 27,
                            Calories = 89m,
                            Carbohydrates = 23m,
                            Category = "Фрукты",
                            Fat = 0.3m,
                            ProductName = "Банан",
                            Protein = 1.1m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 28,
                            Calories = 47m,
                            Carbohydrates = 12m,
                            Category = "Фрукты",
                            Fat = 0.1m,
                            ProductName = "Апельсин",
                            Protein = 0.9m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 29,
                            Calories = 32m,
                            Carbohydrates = 7.7m,
                            Category = "Фрукты",
                            Fat = 0.3m,
                            ProductName = "Клубника",
                            Protein = 0.7m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 30,
                            Calories = 160m,
                            Carbohydrates = 9m,
                            Category = "Фрукты",
                            Fat = 15m,
                            ProductName = "Авокадо",
                            Protein = 2m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 31,
                            Calories = 579m,
                            Carbohydrates = 22m,
                            Category = "Орехи",
                            Fat = 50m,
                            ProductName = "Миндаль",
                            Protein = 21m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 32,
                            Calories = 654m,
                            Carbohydrates = 14m,
                            Category = "Орехи",
                            Fat = 65m,
                            ProductName = "Грецкие орехи",
                            Protein = 15m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 33,
                            Calories = 567m,
                            Carbohydrates = 16m,
                            Category = "Орехи",
                            Fat = 49m,
                            ProductName = "Арахис",
                            Protein = 26m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 34,
                            Calories = 884m,
                            Carbohydrates = 0m,
                            Category = "Масла",
                            Fat = 100m,
                            ProductName = "Оливковое масло",
                            Protein = 0m,
                            Unit = "мл"
                        },
                        new
                        {
                            ProductId = 35,
                            Calories = 717m,
                            Carbohydrates = 0.1m,
                            Category = "Масла",
                            Fat = 81m,
                            ProductName = "Сливочное масло",
                            Protein = 0.9m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 36,
                            Calories = 116m,
                            Carbohydrates = 20m,
                            Category = "Бобовые",
                            Fat = 0.4m,
                            ProductName = "Чечевица вареная",
                            Protein = 9m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 37,
                            Calories = 127m,
                            Carbohydrates = 23m,
                            Category = "Бобовые",
                            Fat = 0.5m,
                            ProductName = "Фасоль",
                            Protein = 9m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 38,
                            Calories = 0m,
                            Carbohydrates = 0m,
                            Category = "Напитки",
                            Fat = 0m,
                            ProductName = "Вода",
                            Protein = 0m,
                            Unit = "мл"
                        },
                        new
                        {
                            ProductId = 39,
                            Calories = 1m,
                            Carbohydrates = 0.3m,
                            Category = "Напитки",
                            Fat = 0m,
                            ProductName = "Чай черный",
                            Protein = 0m,
                            Unit = "мл"
                        },
                        new
                        {
                            ProductId = 40,
                            Calories = 1m,
                            Carbohydrates = 0m,
                            Category = "Напитки",
                            Fat = 0m,
                            ProductName = "Кофе черный",
                            Protein = 0.1m,
                            Unit = "мл"
                        });
                });

            modelBuilder.Entity("NutriPlanner.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Dietitian"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("NutriPlanner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyCalorieTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyCarbsTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyFatTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyProteinTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ActivityLevel = "Moderate",
                            Age = 30,
                            DailyCalorieTarget = 2500m,
                            DailyCarbsTarget = 281m,
                            DailyFatTarget = 83m,
                            DailyProteinTarget = 150m,
                            Email = "admin@nutriplanner.com",
                            Gender = "Male",
                            Goal = "Maintenance",
                            Height = 180m,
                            IsActive = true,
                            PasswordHash = "hashed_password",
                            RegistrationDate = new DateTime(2025, 12, 22, 22, 39, 16, 789, DateTimeKind.Local).AddTicks(9987),
                            RoleId = 3,
                            Username = "admin",
                            Weight = 75m
                        },
                        new
                        {
                            UserId = 2,
                            ActivityLevel = "Moderate",
                            Age = 35,
                            DailyCalorieTarget = 2200m,
                            DailyCarbsTarget = 247m,
                            DailyFatTarget = 73m,
                            DailyProteinTarget = 130m,
                            Email = "dietitian@nutriplanner.com",
                            Gender = "Female",
                            Goal = "Maintenance",
                            Height = 165m,
                            IsActive = true,
                            PasswordHash = "hashed_password",
                            RegistrationDate = new DateTime(2025, 12, 22, 22, 39, 16, 789, DateTimeKind.Local).AddTicks(9999),
                            RoleId = 2,
                            Username = "dietitian",
                            Weight = 60m
                        });
                });

            modelBuilder.Entity("NutriPlanner.Models.Dish", b =>
                {
                    b.HasOne("NutriPlanner.Models.User", "User")
                        .WithMany("Dishes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlanner.Models.DishProduct", b =>
                {
                    b.HasOne("NutriPlanner.Models.Dish", "Dish")
                        .WithMany("DishProducts")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriPlanner.Models.Product", "Product")
                        .WithMany("DishProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NutriPlanner.Models.FoodDiary", b =>
                {
                    b.HasOne("NutriPlanner.Models.Dish", "Dish")
                        .WithMany("FoodDiaries")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NutriPlanner.Models.Product", "Product")
                        .WithMany("FoodDiaries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NutriPlanner.Models.User", "User")
                        .WithMany("FoodDiaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlanner.Models.NutritionPlan", b =>
                {
                    b.HasOne("NutriPlanner.Models.User", "User")
                        .WithMany("NutritionPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlanner.Models.User", b =>
                {
                    b.HasOne("NutriPlanner.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NutriPlanner.Models.Dish", b =>
                {
                    b.Navigation("DishProducts");

                    b.Navigation("FoodDiaries");
                });

            modelBuilder.Entity("NutriPlanner.Models.Product", b =>
                {
                    b.Navigation("DishProducts");

                    b.Navigation("FoodDiaries");
                });

            modelBuilder.Entity("NutriPlanner.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NutriPlanner.Models.User", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("FoodDiaries");

                    b.Navigation("NutritionPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
