// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutriPlanner.Data;

#nullable disable

namespace NutriPlanner.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NutriPlanner.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCalories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCarbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalFat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalProtein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DishId");

                    b.HasIndex("UserId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("NutriPlanner.Models.DishProduct", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DishId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("DishProducts");
                });

            modelBuilder.Entity("NutriPlanner.Models.FoodDiary", b =>
                {
                    b.Property<int>("DiaryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaryId"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DishId")
                        .HasColumnType("int");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DiaryId");

                    b.HasIndex("DishId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("FoodDiaries");
                });

            modelBuilder.Entity("NutriPlanner.Models.NutritionPlan", b =>
                {
                    b.Property<int>("PlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanId"));

                    b.Property<decimal>("DailyCalories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyCarbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyFat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyProtein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("NutritionPlans");
                });

            modelBuilder.Entity("NutriPlanner.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal>("Calories")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Carbohydrates")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Fat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Protein")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductName")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Calories = 165m,
                            Carbohydrates = 0m,
                            Category = "Мясо",
                            Fat = 3.6m,
                            ProductName = "Куриная грудка",
                            Protein = 31m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 2,
                            Calories = 250m,
                            Carbohydrates = 0m,
                            Category = "Мясо",
                            Fat = 15m,
                            ProductName = "Говядина",
                            Protein = 26m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 3,
                            Calories = 130m,
                            Carbohydrates = 28m,
                            Category = "Крупы",
                            Fat = 0.3m,
                            ProductName = "Рис вареный",
                            Protein = 2.7m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 4,
                            Calories = 132m,
                            Carbohydrates = 25m,
                            Category = "Крупы",
                            Fat = 2.3m,
                            ProductName = "Гречка",
                            Protein = 4.5m,
                            Unit = "г"
                        },
                        new
                        {
                            ProductId = 5,
                            Calories = 52m,
                            Carbohydrates = 14m,
                            Category = "Фрукты",
                            Fat = 0.2m,
                            ProductName = "Яблоко",
                            Protein = 0.3m,
                            Unit = "г"
                        });
                });

            modelBuilder.Entity("NutriPlanner.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Admin"
                        });
                });

            modelBuilder.Entity("NutriPlanner.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyCalorieTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyCarbsTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyFatTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DailyProteinTarget")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Goal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Height")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            ActivityLevel = "Moderate",
                            Age = 30,
                            DailyCalorieTarget = 2500m,
                            DailyCarbsTarget = 281m,
                            DailyFatTarget = 83m,
                            DailyProteinTarget = 150m,
                            Email = "admin@nutriplanner.com",
                            Gender = "Male",
                            Goal = "Maintenance",
                            Height = 180m,
                            PasswordHash = "hashed_password",
                            RegistrationDate = new DateTime(2025, 11, 19, 1, 18, 22, 923, DateTimeKind.Local).AddTicks(4181),
                            RoleId = 2,
                            Username = "admin",
                            Weight = 75m
                        });
                });

            modelBuilder.Entity("NutriPlanner.Models.Dish", b =>
                {
                    b.HasOne("NutriPlanner.Models.User", "User")
                        .WithMany("Dishes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlanner.Models.DishProduct", b =>
                {
                    b.HasOne("NutriPlanner.Models.Dish", "Dish")
                        .WithMany("DishProducts")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriPlanner.Models.Product", "Product")
                        .WithMany("DishProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("NutriPlanner.Models.FoodDiary", b =>
                {
                    b.HasOne("NutriPlanner.Models.Dish", "Dish")
                        .WithMany("FoodDiaries")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NutriPlanner.Models.Product", "Product")
                        .WithMany("FoodDiaries")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("NutriPlanner.Models.User", "User")
                        .WithMany("FoodDiaries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlanner.Models.NutritionPlan", b =>
                {
                    b.HasOne("NutriPlanner.Models.User", "User")
                        .WithMany("NutritionPlans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NutriPlanner.Models.User", b =>
                {
                    b.HasOne("NutriPlanner.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NutriPlanner.Models.Dish", b =>
                {
                    b.Navigation("DishProducts");

                    b.Navigation("FoodDiaries");
                });

            modelBuilder.Entity("NutriPlanner.Models.Product", b =>
                {
                    b.Navigation("DishProducts");

                    b.Navigation("FoodDiaries");
                });

            modelBuilder.Entity("NutriPlanner.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NutriPlanner.Models.User", b =>
                {
                    b.Navigation("Dishes");

                    b.Navigation("FoodDiaries");

                    b.Navigation("NutritionPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
